module Translations exposing (I18n, Language(..), currentLanguage, description, greeting, init, language, languageFromString, languageToString, languages, load, welcome)

{-| This file was generated by travelm-agency version 3.8.0.

If you have any issues with the generated code, do not hesitate to open an issue here: <https://github.com/andreasewering/travelm-agency/issues>

-}

import List
import Maybe
import String


{-| Initialize an i18n instance based on a language
-}
init : Language -> I18n
init =
    I18n


{-| Get the currently active language.
-}
currentLanguage : I18n -> Language
currentLanguage (I18n lang) =
    lang


{-| Switch to another i18n instance based on a language
-}
load : Language -> I18n -> I18n
load lang _ =
    init lang


type I18n
    = I18n Language


description : I18n -> String
description (I18n lang) =
    case lang of
        En ->
            "This app demonstrates internationalization with travelm-agency."

        Fr ->
            "Cette application montre l'internationalisation avec travelm-agency."


greeting : String -> I18n -> String
greeting name (I18n lang) =
    case lang of
        En ->
            "Hello, " ++ name ++ "!"

        Fr ->
            "Bonjour, " ++ name ++ " !"


language : I18n -> String
language (I18n lang) =
    case lang of
        En ->
            "Language"

        Fr ->
            "Langue"


welcome : I18n -> String
welcome (I18n lang) =
    case lang of
        En ->
            "Welcome to the i18n example."

        Fr ->
            "Bienvenue dans l'exemple i18n."


{-| Enumeration of the supported languages
-}
type Language
    = En
    | Fr


{-| A list containing all `Language`s. The list is sorted alphabetically.
-}
languages : List Language
languages =
    [ En, Fr ]


{-| Convert a `Language` to its `String` representation.
-}
languageToString : Language -> String
languageToString lang =
    case lang of
        En ->
            "en"

        Fr ->
            "fr"


{-| Maybe parse a `Language` from a `String`.
This will map languages based on the prefix i.e. 'en-US' and 'en' will both map to 'En' unless you provided a 'en-US' translation file.
-}
languageFromString : String -> Maybe Language
languageFromString lang =
    let
        helper langs =
            case langs of
                [] ->
                    Maybe.Nothing

                l :: ls ->
                    if String.startsWith (languageToString l) lang then
                        Maybe.Just l

                    else
                        helper ls
    in
    helper (List.reverse languages)
